/**
 * The Blueprint icon language: node.icon (a plain string set by the Go
 * compiler) maps to a Lucide component here. Unknown names fall back to Box,
 * so the canvas can never crash on an icon it does not recognise. Port of
 * FounderOS v1 components/blueprint/icons.ts on lucide-svelte.
 */
import type { Component } from 'svelte';
import {
	Activity,
	AppWindow,
	BarChart3,
	BookOpen,
	Bot,
	Box,
	Boxes,
	Brain,
	Clapperboard,
	Cloud,
	Code,
	Container,
	Cpu,
	Crosshair,
	Database,
	Filter,
	Folder,
	GitBranch,
	GitCompareArrows,
	Globe,
	Handshake,
	HardDrive,
	Home,
	Keyboard,
	Laptop,
	Layers,
	LayoutDashboard,
	LayoutGrid,
	List,
	ListChecks,
	Map,
	MessageCircle,
	MessageSquare,
	MessagesSquare,
	Mic,
	Monitor,
	Network,
	Play,
	Plug,
	Radar,
	RefreshCw,
	Route,
	Send,
	Server,
	Share2,
	Smartphone,
	Sparkles,
	Square,
	Sunrise,
	Terminal,
	UserRound,
	Users,
	Wallet,
	Wand2,
	Waypoints,
	Workflow,
	Wrench
} from '$lib/founderos/icons';

// lucide-svelte ships legacy class-style typings; the runtime value is a Svelte component.
export type Icon = Component<Record<string, unknown>>;
const c = (x: unknown) => x as Icon;

const ICON_MAP: Record<string, Icon> = {
	box: c(Box),
	'user-round': c(UserRound),
	'wand-2': c(Wand2),
	folder: c(Folder),
	bot: c(Bot),
	plug: c(Plug),
	cpu: c(Cpu),
	sparkles: c(Sparkles),
	database: c(Database),
	'book-open': c(BookOpen),
	list: c(List),
	workflow: c(Workflow),
	radar: c(Radar),
	'messages-square': c(MessagesSquare),
	laptop: c(Laptop),
	server: c(Server),
	send: c(Send),
	'message-circle': c(MessageCircle),
	sunrise: c(Sunrise),
	route: c(Route),
	home: c(Home),
	'message-square': c(MessageSquare),
	filter: c(Filter),
	handshake: c(Handshake),
	'share-2': c(Share2),
	clapperboard: c(Clapperboard),
	crosshair: c(Crosshair),
	wallet: c(Wallet),
	users: c(Users),
	'list-checks': c(ListChecks),
	network: c(Network),
	brain: c(Brain),
	waypoints: c(Waypoints),
	'git-compare-arrows': c(GitCompareArrows),
	wrench: c(Wrench),
	map: c(Map),
	'bar-chart-3': c(BarChart3),
	'layout-grid': c(LayoutGrid),
	layers: c(Layers),
	square: c(Square),
	terminal: c(Terminal),
	'layout-dashboard': c(LayoutDashboard),
	globe: c(Globe),
	play: c(Play),
	'hard-drive': c(HardDrive),
	'refresh-cw': c(RefreshCw),
	activity: c(Activity),
	container: c(Container),
	code: c(Code),
	'app-window': c(AppWindow),
	'git-branch': c(GitBranch),
	smartphone: c(Smartphone),
	monitor: c(Monitor),
	cloud: c(Cloud),
	tailnet: c(Network),
	boxes: c(Boxes),
	keyboard: c(Keyboard),
	mic: c(Mic)
};

export function iconFor(name: string | undefined): Icon {
	return (name && ICON_MAP[name]) || ICON_MAP.box;
}

export const ICON_NAMES = Object.keys(ICON_MAP);
