<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M7 7h10v10"}],["path",{"d":"M7 17 17 7"}]] as [string, Record<string, string>][];
</script>

<Icon name="arrow-up-right" {...props} {iconNode} />
