<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"m12 19-7-7 7-7"}],["path",{"d":"M19 12H5"}]] as [string, Record<string, string>][];
</script>

<Icon name="arrow-left" {...props} {iconNode} />
