<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"m7 7 10 10"}],["path",{"d":"M17 7v10H7"}]] as [string, Record<string, string>][];
</script>

<Icon name="arrow-down-right" {...props} {iconNode} />
