<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M9 5v4"}],["rect",{"width":"4","height":"6","x":"7","y":"9","rx":"1"}],["path",{"d":"M9 15v2"}],["path",{"d":"M17 3v2"}],["rect",{"width":"4","height":"8","x":"15","y":"5","rx":"1"}],["path",{"d":"M17 13v3"}],["path",{"d":"M3 3v16a2 2 0 0 0 2 2h16"}]] as [string, Record<string, string>][];
</script>

<Icon name="candlestick-chart" {...props} {iconNode} />
