<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["polyline",{"points":"12 6 12 12 16 14"}]] as [string, Record<string, string>][];
</script>

<Icon name="clock" {...props} {iconNode} />
