<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polyline",{"points":"16 18 22 12 16 6"}],["polyline",{"points":"8 6 2 12 8 18"}]] as [string, Record<string, string>][];
</script>

<Icon name="code" {...props} {iconNode} />
