<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polyline",{"points":"9 10 4 15 9 20"}],["path",{"d":"M20 4v7a4 4 0 0 1-4 4H4"}]] as [string, Record<string, string>][];
</script>

<Icon name="corner-down-left" {...props} {iconNode} />
