<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polyline",{"points":"9 14 4 9 9 4"}],["path",{"d":"M20 20v-7a4 4 0 0 0-4-4H4"}]] as [string, Record<string, string>][];
</script>

<Icon name="corner-up-left" {...props} {iconNode} />
