<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polygon",{"points":"22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"}]] as [string, Record<string, string>][];
</script>

<Icon name="filter" {...props} {iconNode} />
