<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"}],["path",{"d":"M12 17h.01"}]] as [string, Record<string, string>][];
</script>

<Icon name="help-circle" {...props} {iconNode} />
