<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}],["circle",{"cx":"9","cy":"9","r":"2"}],["path",{"d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}]] as [string, Record<string, string>][];
</script>

<Icon name="image" {...props} {iconNode} />
