<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M21 12a9 9 0 1 1-6.219-8.56"}]] as [string, Record<string, string>][];
</script>

<Icon name="loader-2" {...props} {iconNode} />
