<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M7.9 20A9 9 0 1 0 4 16.1L2 22Z"}]] as [string, Record<string, string>][];
</script>

<Icon name="message-circle" {...props} {iconNode} />
