<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M5 12h14"}]] as [string, Record<string, string>][];
</script>

<Icon name="minus" {...props} {iconNode} />
