<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polygon",{"points":"6 3 20 12 6 21 6 3"}]] as [string, Record<string, string>][];
</script>

<Icon name="play" {...props} {iconNode} />
