<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M12 22v-5"}],["path",{"d":"M9 8V2"}],["path",{"d":"M15 8V2"}],["path",{"d":"M18 8v5a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V8Z"}]] as [string, Record<string, string>][];
</script>

<Icon name="plug" {...props} {iconNode} />
