<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["polyline",{"points":"22 17 13.5 8.5 8.5 13.5 2 7"}],["polyline",{"points":"16 17 22 17 22 11"}]] as [string, Record<string, string>][];
</script>

<Icon name="trending-down" {...props} {iconNode} />
