<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M9 14 4 9l5-5"}],["path",{"d":"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"}]] as [string, Record<string, string>][];
</script>

<Icon name="undo-2" {...props} {iconNode} />
