<!-- generated by scripts/gen-founderos-icons.mjs from lucide-react 0.441 (FounderOS v1) -->
<script lang="ts">
	import { Icon } from 'lucide-svelte';
	let props: Record<string, unknown> = $props();
	const iconNode = [["path",{"d":"M18 6 6 18"}],["path",{"d":"m6 6 12 12"}]] as [string, Record<string, string>][];
</script>

<Icon name="x" {...props} {iconNode} />
