<!-- Buy/sell (FounderOS v1 TradingBoard ActionTag): a small bold tag in the
     side's status color. Prod's tint (bg-os-ok/15 on a var() color) is never
     generated by its Tailwind, so it renders as colored type alone; so does
     this. -->
<script lang="ts">
	let { action }: { action: string } = $props();
</script>

<span
	data-part="action-tag"
	class="shrink-0 justify-self-start rounded-[4px] px-1.5 py-0.5 font-mono text-[9px] font-bold uppercase tracking-wider"
	style="color: {action === 'buy' ? 'var(--bn-ok)' : 'var(--bn-err)'}">{action}</span
>
